HYDRA_FULL_ERROR=1 uv run thirdparty/BenchMARL/benchmarl/run.py -m \
  algorithm=mappo \
  task=pettingzoo/simple_tag \
  model=layers/mlp \
  critic_model=\${model} \
  seed=0 \
  experiment.max_n_frames=245760 \
  experiment.train_device=cuda \
  experiment.sampling_device=cuda \
  experiment.buffer_device=cpu \
  experiment.render=false \
  experiment.on_policy_n_envs_per_worker=2 \
  experiment.on_policy_collected_frames_per_batch=4096 \
  experiment.evaluation_interval=12288 \
  experiment.on_policy_minibatch_size=256 \
  experiment.on_policy_n_minibatch_iters=4 \
  algorithm.entropy_coef=0.01 \
  experiment.lr=3e-4 \
  "experiment.loggers=[csv]"