HYDRA_FULL_ERROR=1 uv run thirdparty/BenchMARL/benchmarl/run.py -m \
  algorithm=vdn \
  task=vmas/balance \
  model=layers/mlp \
  critic_model=\${model} \
  seed=0 \
  experiment.max_n_frames=245760 \
  experiment.train_device=cuda \
  experiment.sampling_device=cuda \
  experiment.buffer_device=cpu \
  experiment.render=false \
  experiment.off_policy_n_envs_per_worker=2 \
  experiment.off_policy_n_optimizer_steps=1000 \
  experiment.off_policy_collected_frames_per_batch=4096 \
  experiment.evaluation_interval=12288 \
  experiment.off_policy_n_optimizer_steps=45 \
  experiment.off_policy_train_batch_size=128 \
  experiment.lr=5e-5 \
  task.n_agents=2 \
  task.max_steps=100 \
  task.random_package_pos_on_line=True \
  task.package_mass=5 \
  "experiment.loggers=[csv]"
